import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const profilePageStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    bannerContainer: {
        width: width,
        height: height * 0.25,
        position: 'relative',
    },
    bannerPicture: {
        width: width,
        height: height * 0.25,
    },

    addButton: {
        position: 'absolute',
        bottom: -47,  // Changed from -50 to -20 to move it up
        right: 20,
        backgroundColor: '#000000',
        borderRadius: 25,
        paddingVertical: 10,
        paddingHorizontal: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        borderWidth: 1,
        borderColor: '#FFFFFF',
        zIndex: 999, // Add this to ensure button is clickable
    },
    addButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontFamily: 'Inter_600SemiBold',
        fontWeight: '600',
    },
    profileIconContainer: {
        alignItems: 'flex-start',
        paddingHorizontal: 20,
        marginTop: -50,
        marginBottom: 10,
        position: 'relative',
        zIndex: 5, // Ensure profile circle is above banner
    },
    profileCircleWrapper: {
        width: 100,
        height: 100,
        backgroundColor: '#FFFFFF',
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileCircle: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        overflow: 'hidden',
        position: 'relative',
    },
    profileImage: {
        width: 94,
        height: 94,
        borderRadius: 47,
        resizeMode: 'cover',
    },
    profileStats: {
        paddingHorizontal: 20,
        marginTop: 10,
        marginBottom: 20,
    },
    username: {
        fontSize: 24,
        fontFamily: 'Inter_700Bold',
        color: '#1C1E21',
        marginBottom: 16,
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: 'white',
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 20,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    statItem: {
        flex: 1,
        alignItems: 'center',
    },
    statNumber: {
        fontSize: 20,
        fontFamily: 'Inter_700Bold',
        color: '#1C1E21',
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 13,
        fontFamily: 'Inter_400Regular',
        color: '#65676B',
    },
    editProfileButton: {
        backgroundColor: '#E4E6EB',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        marginBottom: 20,
    },
    editProfileButtonText: {
        fontSize: 16,
        fontFamily: 'Inter_600SemiBold',
        color: '#1C1E21',
    },
    cardsSection: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 18,
        fontFamily: 'Inter_700Bold',
        color: '#1C1E21',
        marginBottom: 16,
    },
    cardsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    trippyCard: {
        width: (width - 60) / 2, // 2 columns with spacing
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        position: 'relative',
    },
    cardIconContainer: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#F0F2F5',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    cardTitle: {
        fontSize: 14,
        fontFamily: 'Inter_600SemiBold',
        color: '#1C1E21',
        marginBottom: 4,
        textAlign: 'center',
    },
    cardSubtitle: {
        fontSize: 12,
        fontFamily: 'Inter_400Regular',
        color: '#65676B',
        textAlign: 'center',
    },
    achievementBadge: {
        position: 'absolute',
        top: -8,
        right: -8,
        backgroundColor: '#FF6B6B',
        borderRadius: 12,
        minWidth: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 6,
        borderWidth: 2,
        borderColor: 'white',
    },
    badgeText: {
        fontSize: 12,
        fontFamily: 'Inter_700Bold',
        color: 'white',
    },
    placeholderContent: {
        paddingHorizontal: 20,
        paddingVertical: 40,
        alignItems: 'center',
    },
    placeholderText: {
        fontSize: 14,
        fontFamily: 'Inter_400Regular',
        color: '#65676B',
    },
});